# Generated by Django 3.2.3 on 2021-05-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('event', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('mobile', models.CharField(max_length=200)),
                ('altmobile', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=100)),
                ('description', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='', max_length=20)),
                ('lname', models.CharField(default='', max_length=20)),
                ('email', models.CharField(default='', max_length=20)),
                ('mobile', models.CharField(default='', max_length=20)),
                ('address', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
