# Generated by Django 3.2.3 on 2021-05-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210518_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('event', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('date', models.DateField(blank=True)),
                ('mobile', models.CharField(max_length=200)),
                ('altmobile', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=100)),
                ('description', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
