# Generated by Django 3.2.3 on 2021-05-18 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userevents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userevents',
            old_name='event',
            new_name='eventname',
        ),
        migrations.RenameField(
            model_name='userevents',
            old_name='username',
            new_name='name',
        ),
    ]
