# Generated by Django 3.2.3 on 2021-05-18 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210518_1800'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingEvent',
        ),
    ]
